# Generated by Django 6.0.6 on 2026-06-16 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('informacion_consultorio', models.TextField(blank=True, help_text='Dirección y datos del consultorio', verbose_name='información del consultorio')),
                ('precio_consulta', models.DecimalField(decimal_places=2, default=0, help_text='Precio de la consulta médica', max_digits=10, verbose_name='precio consulta')),
                ('atencion_online', models.BooleanField(default=False, help_text='Indica si ofrece atención virtual', verbose_name='atención online')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio del médico', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='calificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_datos_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_datos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del horario disponible', verbose_name='fecha')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno', verbose_name='hora inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno', verbose_name='hora fin')),
                ('disponible', models.BooleanField(default=True, help_text='Indica si el turno está disponible', verbose_name='disponible')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicos.medico', verbose_name='médico')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['fecha', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'fecha', 'hora_inicio', 'hora_fin'), name='unique_medico_fecha_horario'), models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='check_hora_fin_gt_hora_inicio')],
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si esta es la especialidad principal del médico', verbose_name='es principal')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='especialidades.especialidad', verbose_name='especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='medicos.medico', verbose_name='médico')),
            ],
            options={
                'verbose_name': 'especialidad del médico',
                'verbose_name_plural': 'especialidades de los médicos',
                'ordering': ['medico', 'especialidad'],
                'unique_together': {('medico', 'especialidad')},
            },
        ),
    ]
