# Generated by Django 6.0.6 on 2026-06-16 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rol (ej: administrador, recepcionista)', max_length=50, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol y sus responsabilidades', verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('correo', models.EmailField(help_text='Dirección de correo electrónico del usuario', max_length=255, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(help_text='Apellido del usuario', max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='teléfono')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('paciente', 'Paciente')], default='paciente', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo', verbose_name='activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_matricula', models.CharField(help_text='Número de matrícula profesional', max_length=20, unique=True, verbose_name='número de matrícula')),
                ('bio', models.TextField(blank=True, help_text='Resumen profesional del médico', verbose_name='biografía')),
                ('telefono_consultorio', models.CharField(blank=True, max_length=20, verbose_name='teléfono consultorio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_historia_clinica', models.CharField(blank=True, help_text='Número único de historia clínica', max_length=20, unique=True, verbose_name='número de historia clínica')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, help_text='Dirección del paciente', verbose_name='dirección')),
                ('obra_social', models.CharField(blank=True, help_text='Obra social o prepaga del paciente', max_length=100, verbose_name='obra social')),
                ('numero_afiliado', models.CharField(blank=True, help_text='Número de afiliado a la obra social', max_length=50, verbose_name='número de afiliado')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=200, verbose_name='nombre contacto emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono contacto emergencia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['usuario__apellido', 'usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token de recuperación', max_length=255, unique=True, verbose_name='token')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('utilizado', models.BooleanField(default=False, help_text='Indica si el token ya fue utilizado', verbose_name='utilizado')),
                ('expira_en', models.DateTimeField(help_text='Fecha y hora de expiración del token', verbose_name='expira en')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de recuperación',
                'verbose_name_plural': 'tokens de recuperación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
