# Generated by Django 6.0.6 on 2026-06-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(blank=True, help_text='Documento de identidad', max_length=30, null=True, unique=True, verbose_name='documento'),
        ),
    ]
