# Generated by Django 6.0.6 on 2026-06-16 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del estado (pendiente, confirmada, realizada, cancelada, no_asistio)', max_length=50, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del estado', verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'estado de cita',
                'verbose_name_plural': 'estados de citas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField(help_text='Motivo de la consulta', verbose_name='motivo')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la cita', verbose_name='notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='medicos.horario', unique=True, verbose_name='horario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='medicos.medico', verbose_name='médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='accounts.paciente', verbose_name='paciente')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.estadocita', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
                ('nota', models.TextField(blank=True, help_text='Nota explicativa del cambio', verbose_name='nota')),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_citas', to=settings.AUTH_USER_MODEL, verbose_name='cambiado por')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='citas.cita', verbose_name='cita')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='citas.estadocita', verbose_name='estado anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='citas.estadocita', verbose_name='estado nuevo')),
            ],
            options={
                'verbose_name': 'auditoría de cita',
                'verbose_name_plural': 'auditorías de citas',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
