# Generated by Django 6.0.6 on 2026-06-29 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('citas', '0002_seed_estados_cita'),
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostico', models.TextField(help_text='Diagnóstico del paciente', verbose_name='diagnóstico')),
                ('tratamiento', models.TextField(blank=True, help_text='Tratamiento recetado', verbose_name='tratamiento')),
                ('notas', models.TextField(blank=True, help_text='Notas clínicas adicionales', verbose_name='notas adicionales')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='citas.cita', verbose_name='cita')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='medicos.medico', verbose_name='médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='accounts.paciente', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
